### ISSUE TITLE
Launching the application in the emulator

### ISSUE THREAD

**Issue by bezvozni** [SpheroidUniverse/SpheroidScript#7]
I would like to bring this issue up for discussion between community members and developers. Can I do it here?

I try to run the application in emulation according to the instructions https://developers.google.com/ar/develop/java/emulator, 
but I get an inevitable crash of the application. 
Log:

>      --------- beginning of crash
> 2020-08-24 11:33:05.822 7448-7448/? A/libc: Fatal signal 4 (SIGILL), code -6 (SI_TKILL) in tid 7448 (spheroidandroid), pid 7448 (spheroidandroid)
> 2020-08-24 11:33:05.946 7488-7488/? I/crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
> 2020-08-24 11:33:05.947 253-253/? I/tombstoned: received crash request for pid 7448
> 2020-08-24 11:33:05.967 7488-7488/? I/crash_dump32: performing dump of process 7448 (target tid = 7448)
> 2020-08-24 11:33:06.055 7488-7488/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> 2020-08-24 11:33:06.055 7488-7488/? A/DEBUG: Build fingerprint: 'google/sdk_gphone_x86/generic_x86_arm:11/RPB3.200720.005/6705141:user/release-keys'
> 2020-08-24 11:33:06.055 7488-7488/? A/DEBUG: Revision: '0'
> 2020-08-24 11:33:06.056 7488-7488/? A/DEBUG: ABI: 'x86'
> 2020-08-24 11:33:06.058 7488-7488/? A/DEBUG: Timestamp: 2020-08-24 08:33:06+0000
> 2020-08-24 11:33:06.058 7488-7488/? A/DEBUG: pid: 7448, tid: 7448, name: spheroidandroid  >>> io.spheroid.spheroidandroid <<<
> 2020-08-24 11:33:06.058 7488-7488/? A/DEBUG: uid: 10152
> 2020-08-24 11:33:06.058 7488-7488/? A/DEBUG: signal 4 (SIGILL), code -6 (SI_TKILL), fault addr --------
> 2020-08-24 11:33:06.058 7488-7488/? A/DEBUG:     eax 00000000  ebx 00001d18  ecx 00001d18  edx 00000004
> 2020-08-24 11:33:06.058 7488-7488/? A/DEBUG:     edi 00000004  esi 00001d18
> 2020-08-24 11:33:06.058 7488-7488/? A/DEBUG:     ebp fff2e348  esp fff2e2fc  eip f602db99
> 2020-08-24 11:33:06.142 1596-2038/? W/FuseDaemon: Invalid other package file access from com.google.android.gm(: /storage/17FF-2E13/Android/data/com.google.android.gm: No such file or directory
> 2020-08-24 11:33:06.170 2783-2803/? E/DatabaseUtils: Writing exception to parcel
>     java.lang.SecurityException: Unsupported path /82ba84d554e318430429a80933c734c4
>         at com.android.providers.downloads.DownloadProvider.checkFileUriDestination(DownloadProvider.java:1096)
>         at com.android.providers.downloads.DownloadProvider.insert(DownloadProvider.java:730)
>         at android.content.ContentProvider.insert(ContentProvider.java:1673)
>         at android.content.ContentProvider$Transport.insert(ContentProvider.java:336)
>         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:167)
>         at android.os.Binder.execTransactInternal(Binder.java:1154)
>         at android.os.Binder.execTransact(Binder.java:1123)
> 2020-08-24 11:33:06.189 7488-7488/? A/DEBUG: backtrace:
> 2020-08-24 11:33:06.189 7488-7488/? A/DEBUG:       #00 pc 00000b99  [vdso] (__kernel_vsyscall+9)
> 2020-08-24 11:33:06.189 7488-7488/? A/DEBUG:       #01 pc 000ccaac  /apex/com.android.runtime/lib/bionic/libc.so (tgkill+28) (BuildId: 787473e23bc7d49ac38e635c3435c37a)
> 2020-08-24 11:33:06.189 7488-7488/? A/DEBUG:       #02 pc 00084bd4  /apex/com.android.runtime/lib/bionic/libc.so (raise+68) (BuildId: 787473e23bc7d49ac38e635c3435c37a)
> 2020-08-24 11:33:06.189 7488-7488/? A/DEBUG:       #03 pc 000d0602  /system/lib/libndk_translation.so (ndk_translation::UndefinedInsn(ndk_translation::ProcessState*, char const*)+114) (BuildId: 5977e6ead95c453c31683e470b3b02ad)
> 2020-08-24 11:33:06.189 7488-7488/? A/DEBUG:       #04 pc 000e0acc  /system/lib/libndk_translation.so (ndk_translation::InsnInterpreter::CallInterp(unsigned int, void const*, void const*)+44) (BuildId: 5977e6ead95c453c31683e470b3b02ad)
> 2020-08-24 11:33:06.189 7488-7488/? A/DEBUG:       #05 pc 00117a49  /system/lib/libndk_translation.so (ndk_translation::GenReportInsnNotImplHelper(ndk_translation::ArmSemanticsDecoderHooks*, unsigned int, char const*)+73) (BuildId: 5977e6ead95c453c31683e470b3b02ad)
> 2020-08-24 11:33:06.189 7488-7488/? A/DEBUG:       #06 pc 000fc56b  /system/lib/libndk_translation.so (ndk_translation::SemanticsDecoder::SEVL(ndk_translation::SEVL_Args const&)+43) (BuildId: 5977e6ead95c453c31683e470b3b02ad)
> 2020-08-24 11:33:06.189 7488-7488/? A/DEBUG:       #07 pc 0013358b  /system/lib/libndk_translation.so (ndk_translation::ArmDecoder::TranslateThumbInsn(unsigned short const*)+30795) (BuildId: 5977e6ead95c453c31683e470b3b02ad)
> 2020-08-24 11:33:06.189 7488-7488/? A/DEBUG:       #08 pc 000e1de0  /system/lib/libndk_translation.so (ndk_translation::(anonymous namespace)::DecodeInsn(unsigned int, ndk_translation::(anonymous namespace)::ArmInterpreter*, ndk_translation::ProcessState*, ndk_translation::ArmDecoder*)+128) (BuildId: 5977e6ead95c453c31683e470b3b02ad)
> 2020-08-24 11:33:06.189 7488-7488/? A/DEBUG:       #09 pc 000e2014  /system/lib/libndk_translation.so (ndk_translation::InterpretTrace(ndk_translation::ProcessState*)+340) (BuildId: 5977e6ead95c453c31683e470b3b02ad)
> 2020-08-24 11:33:06.190 7488-7488/? A/DEBUG:       #10 pc 000d1583  /system/lib/libndk_translation.so (ndk_translation_HandleNotTranslated+99) (BuildId: 5977e6ead95c453c31683e470b3b02ad)
> 2020-08-24 11:33:06.190 7488-7488/? A/DEBUG:       #11 pc 000cf9be  /system/lib/libndk_translation.so (ndk_translation::ExecuteGuest(ndk_translation::ProcessState*, unsigned int)+238) (BuildId: 5977e6ead95c453c31683e470b3b02ad)
> 2020-08-24 11:33:06.190 7488-7488/? A/DEBUG:       #12 pc 000cfbf6  /system/lib/libndk_translation.so (ndk_translation::(anonymous namespace)::RunGuestCall(unsigned int, int, int, unsigned int*)+262) (BuildId: 5977e6ead95c453c31683e470b3b02ad)
> 2020-08-24 11:33:06.190 7488-7488/? A/DEBUG:       #13 pc 000cfd5a  /system/lib/libndk_translation.so (ndk_translation::RunGuestCall(unsigned int, ndk_translation::GuestArgumentBuffer*)+42) (BuildId: 5977e6ead95c453c31683e470b3b02ad)
> 2020-08-24 11:33:06.190 7488-7488/? A/DEBUG:       #14 pc 000d2b8a  /system/lib/libndk_translation.so (ndk_translation::(anonymous namespace)::RunGuestJNIFunction(unsigned int, ndk_translation::GuestArgumentBuffer*)+74) (BuildId: 5977e6ead95c453c31683e470b3b02ad)
> 2020-08-24 11:33:06.190 7488-7488/? A/DEBUG:       #15 pc 0007c85b  <anonymous:c73d3000>
> 2020-08-24 11:33:06.246 343-343/? I/perfetto: probes_producer.cc:329  Producer stop (id=10)
> 2020-08-24 11:33:06.275 344-344/? I/perfetto: ng_service_impl.cc:1948 Tracing session 10 ended, total sessions:0
> 2020-08-24 11:33:06.276 343-343/? I/perfetto: ftrace_procfs.cc:183    disabled ftrace
> 2020-08-24 11:33:06.569 253-253/? E/tombstoned: Tombstone written to: /data/tombstones/tombstone_18

Nevertheless. Can we figure out what's the matter? Perhaps the emulator does not emulate some kind of sensor? Or does this sensor just need to be enabled / configured? Is it possible to understand something from the log? Perhaps you need some more research activities to get information? I am ready to make them. But I don’t understand in which direction to look.

**Comment by Mind-Vii** [comment]
...

**Comment by Mind-Vii** [comment]
We could ...
